-- Create daily_payroll_reports table for automated daily calculations
CREATE TABLE IF NOT EXISTS `daily_payroll_reports` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `employee_id` INT NOT NULL,
    `report_date` DATE NOT NULL,
    `report_year` INT NOT NULL,
    `report_month` INT NOT NULL,
    `report_day` INT NOT NULL,
    `week_number` INT NOT NULL DEFAULT 1,
    `branch_id` INT DEFAULT NULL,
    `days_worked` DECIMAL(4,1) DEFAULT 0,
    `total_hours` DECIMAL(8,2) DEFAULT 0,
    `daily_rate` DECIMAL(10,2) DEFAULT 0,
    `basic_pay` DECIMAL(10,2) DEFAULT 0,
    `ot_hours` DECIMAL(6,2) DEFAULT 0,
    `ot_rate` DECIMAL(10,2) DEFAULT 0,
    `ot_amount` DECIMAL(10,2) DEFAULT 0,
    `performance_allowance` DECIMAL(10,2) DEFAULT 0,
    `gross_pay` DECIMAL(10,2) DEFAULT 0,
    `gross_plus_allowance` DECIMAL(10,2) DEFAULT 0,
    `ca_deduction` DECIMAL(10,2) DEFAULT 0,
    `sss_deduction` DECIMAL(10,2) DEFAULT 0,
    `philhealth_deduction` DECIMAL(10,2) DEFAULT 0,
    `pagibig_deduction` DECIMAL(10,2) DEFAULT 0,
    `sss_loan` DECIMAL(10,2) DEFAULT 0,
    `total_deductions` DECIMAL(10,2) DEFAULT 0,
    `take_home_pay` DECIMAL(10,2) DEFAULT 0,
    `status` VARCHAR(20) DEFAULT 'Pending',
    `created_by` INT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY `unique_emp_date_branch` (`employee_id`, `report_date`, `branch_id`),
    KEY `idx_report_date` (`report_date`),
    KEY `idx_employee` (`employee_id`),
    KEY `idx_year_month` (`report_year`, `report_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
