<?php

return [
    'select_employee.php' => "Page: Select Employee (Attendance)\n\nWhat this page does:\n- Lets you select a deployment branch and manage attendance for employees assigned to that branch.\n\nHow to use:\n1) Select a deployment branch from the cards at the top.\n2) Use the Filters dropdown:\n   - Available: employees with no attendance today (and/or already timed-out if time columns exist).\n   - Summary: shows employees for the selected branch with their latest status today.\n   - Present: employees currently timed-in (open shift) in the selected branch.\n   - Absent: employees explicitly marked Absent today.\n3) Actions per employee:\n   - Absent button: marks employee as Absent (creates today’s attendance row if none exists).\n   - Time In / Time Out button: logs attendance.\n     - Disabled if employee is marked Absent.\n4) Menu (three dots) options:\n   - Time Logs Today: view time-in/out logs for today.\n   - Overtime: adjust overtime hours if allowed.\n   - Transfer: move employee to another branch (if enabled).\n   - Undo last action: reverts the latest attendance action.\n\nCommon questions:\n- If you can’t mark Time In/Out, confirm a branch is selected and the employee is not marked Absent.\n",

    'employees.php' => "Page: Employees (Management)\n\nWhat this page does:\n- Lets Super Admin/Admin manage employee records (view, search, add, edit).\n\nHow to use:\n1) Use the Search box to find employees by name/ID.\n2) Use pagination controls to navigate pages and change page size.\n3) Use Add Employee to create a new worker record (if your role allows it).\n4) Use Edit to update employee details (name, contact, status, position, etc.).\n\nTips:\n- If edits are not saving, confirm you are logged in with the correct role (Super Admin usually required).\n",

    'settings.php' => "Page: Settings\n\nWhat this page does:\n- Lets you manage your account profile, password, and (for admins) system tools.\n\nHow to use:\n1) Use the left-side tabs to switch between settings sections.\n2) Update Profile: change name/email/profile image.\n3) Change Password: enter current + new password and confirm.\n4) Admin/System Tools (if visible): perform system-level actions like backups or diagnostics.\n\nTips:\n- If you don’t see admin tools, your current role may not have access.\n",

    'default' => "General Help\n\nTell me what page you are on and what you are trying to do (e.g., mark attendance, add employee, change password). I can guide you step-by-step.\n"
];
